build:
  image: visioneers/docker-phoenix:latest
  commands:
    - npm install -g phantomjs
    - mix deps.get
    - mix ecto.create ecto.migrate
    - mix test

compose:
  postgres:
    image: postgres:9.6
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
