name: Elixir CI

on: push

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image: elixir:1.9.1
      env:
        MIX_ENV: test

    services:
      postgres:
        image: postgres
        ports:
          - 5432:5432
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - uses: actions/checkout@v1

      - uses: actions/setup-node@v1
        with:
          node-version: 10

      - name: Install system packages
        run: |
          curl https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb -o /chrome.deb
          dpkg -i /chrome.deb || apt-get install -yf
          rm /chrome.deb
          curl https://chromedriver.storage.googleapis.com/2.31/chromedriver_linux64.zip -o /usr/local/bin/chromedriver
          chmod +x /usr/local/bin/chromedriver
          chromedriver --version

      - name: Install Dependencies
        run: |
          mix local.rebar --force
          mix local.hex --force
          mix deps.get
          cd assets
          npm install -g yarn
          yarn
          cd ..

      - name: Run Tests
        run: mix test
        env:
          DATABASE_POSTGRESQL_HOSTNAME: postgres
